### 제목과 내용에 따른 신뢰도 등급 분류 학습
- 사용데이터 : trade_classification_data.csv (ai 생성)

In [1]:
import pandas as pd

post_df = pd.read_csv('./datasets/trade_classification_data.csv')
post_df

,title,content,target
0,긴급 한국산 조선 기자재 동남아 수출,현재 동남아 3개국 판매 네트워크 보유 중입니다. 수출 경험 풍부하며 현지 통관 지...,정상
1,직거래 - 터키산 섬유 원단 수입 거래처 모집,NaN,정상
2,직거래 - 한국산 자동차 부품 미국 수출,국내 제조사로 품질 및 납기 보장 가능합니다. CE 및 KC 인증 보유하고 있으며 ...,정상
3,중국산 희토류 정기 수입 문의,검증된 물건이지만 출처는 말씀드리기 어렵습니다. 믿고 거래하셔도 됩니다.,의심
4,조건 협의 가능 연락주세요,가격이 말도 안 되게 싸죠? 사정이 있어서 그렇습니다. 연락주세요.,의심
...,...,...,...
20795,010-1234-5678 바로 연락주세요,합법적인 방법으로 월 천만원 수익 가능합니다. 자세한 내용은 카톡으로 문의주세요.,검토필요
20796,직거래 - 한국산 자동차 부품 미국 수출,FOB 조건으로 월 500톤 공급 가능합니다. 품질 인증서 및 검사 성적서 구비되어...,정상
20797,NaN,개인 사정으로 인해 자세한 내용은 공개하기 어렵습니다. 연락주시면 설명드리겠습니다.,의심
20798,대량 중동산 원유 파생 제품 수입 희망,품질 등급 A급 기준이며 수입 통관 경험 다수 보유하고 있습니다. L/C at si...,정상
20799,짝퉁 명품 초저가 판매,임시 내용입니다 나중에 수정할 예정입니다,검토필요

In [2]:
post_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    20280 non-null  object
 1   content  20280 non-null  object
 2   target   20800 non-null  object
dtypes: object(3)
memory usage: 487.6+ KB

In [3]:
post_df.isna().sum()

title      520
content    520
target       0
dtype: int64

In [4]:
post_df = post_df[~post_df.title.isna()]
post_df = post_df[~post_df.content.isna()]
post_df

,title,content,target
0,긴급 한국산 조선 기자재 동남아 수출,현재 동남아 3개국 판매 네트워크 보유 중입니다. 수출 경험 풍부하며 현지 통관 지...,정상
2,직거래 - 한국산 자동차 부품 미국 수출,국내 제조사로 품질 및 납기 보장 가능합니다. CE 및 KC 인증 보유하고 있으며 ...,정상
3,중국산 희토류 정기 수입 문의,검증된 물건이지만 출처는 말씀드리기 어렵습니다. 믿고 거래하셔도 됩니다.,의심
4,조건 협의 가능 연락주세요,가격이 말도 안 되게 싸죠? 사정이 있어서 그렇습니다. 연락주세요.,의심
6,해외 도박 사이트 총판,불법 총기 부품 구합니다 조용히 거래 원합니다,검토필요
...,...,...,...
20794,한국산 전자부품 동남아 수출 거래처 모집,수입 관세 및 통관 절차 전반에 대한 지원 가능합니다. 관련 서류 일체 당사가 준비...,정상
20795,010-1234-5678 바로 연락주세요,합법적인 방법으로 월 천만원 수익 가능합니다. 자세한 내용은 카톡으로 문의주세요.,검토필요
20796,직거래 - 한국산 자동차 부품 미국 수출,FOB 조건으로 월 500톤 공급 가능합니다. 품질 인증서 및 검사 성적서 구비되어...,정상
20798,대량 중동산 원유 파생 제품 수입 희망,품질 등급 A급 기준이며 수입 통관 경험 다수 보유하고 있습니다. L/C at si...,정상
20799,짝퉁 명품 초저가 판매,임시 내용입니다 나중에 수정할 예정입니다,검토필요

In [5]:
post_df.duplicated().sum()

np.int64(10702)

In [6]:
post_df.drop_duplicates(inplace=True, ignore_index=True)
post_df

,title,content,target
0,긴급 한국산 조선 기자재 동남아 수출,현재 동남아 3개국 판매 네트워크 보유 중입니다. 수출 경험 풍부하며 현지 통관 지...,정상
1,직거래 - 한국산 자동차 부품 미국 수출,국내 제조사로 품질 및 납기 보장 가능합니다. CE 및 KC 인증 보유하고 있으며 ...,정상
2,중국산 희토류 정기 수입 문의,검증된 물건이지만 출처는 말씀드리기 어렵습니다. 믿고 거래하셔도 됩니다.,의심
3,조건 협의 가능 연락주세요,가격이 말도 안 되게 싸죠? 사정이 있어서 그렇습니다. 연락주세요.,의심
4,해외 도박 사이트 총판,불법 총기 부품 구합니다 조용히 거래 원합니다,검토필요
...,...,...,...
9073,직거래 - 인도산 면화 원자재 정기 구매 희망,국제 품질 기준을 충족하며 제3자 검사 기관 검사 완료된 제품입니다. T/T 또는 ...,정상
9074,신규 바이어 모집 - 페루산 아연 원광 수입 문의,정기 수입 바이어를 모집합니다. 월 최소 100톤 이상 구매 가능한 업체 우선 협의...,정상
9075,한국산 전자부품 동남아 수출 거래처 모집,수입 관세 및 통관 절차 전반에 대한 지원 가능합니다. 관련 서류 일체 당사가 준비...,정상
9076,직거래 - 한국산 자동차 부품 미국 수출,FOB 조건으로 월 500톤 공급 가능합니다. 품질 인증서 및 검사 성적서 구비되어...,정상
9077,대량 중동산 원유 파생 제품 수입 희망,품질 등급 A급 기준이며 수입 통관 경험 다수 보유하고 있습니다. L/C at si...,정상

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
targets = encoder.fit_transform(post_df.target)

post_df.target = targets
post_df

,title,content,target
0,긴급 한국산 조선 기자재 동남아 수출,현재 동남아 3개국 판매 네트워크 보유 중입니다. 수출 경험 풍부하며 현지 통관 지...,2
1,직거래 - 한국산 자동차 부품 미국 수출,국내 제조사로 품질 및 납기 보장 가능합니다. CE 및 KC 인증 보유하고 있으며 ...,2
2,중국산 희토류 정기 수입 문의,검증된 물건이지만 출처는 말씀드리기 어렵습니다. 믿고 거래하셔도 됩니다.,1
3,조건 협의 가능 연락주세요,가격이 말도 안 되게 싸죠? 사정이 있어서 그렇습니다. 연락주세요.,1
4,해외 도박 사이트 총판,불법 총기 부품 구합니다 조용히 거래 원합니다,0
...,...,...,...
9073,직거래 - 인도산 면화 원자재 정기 구매 희망,국제 품질 기준을 충족하며 제3자 검사 기관 검사 완료된 제품입니다. T/T 또는 ...,2
9074,신규 바이어 모집 - 페루산 아연 원광 수입 문의,정기 수입 바이어를 모집합니다. 월 최소 100톤 이상 구매 가능한 업체 우선 협의...,2
9075,한국산 전자부품 동남아 수출 거래처 모집,수입 관세 및 통관 절차 전반에 대한 지원 가능합니다. 관련 서류 일체 당사가 준비...,2
9076,직거래 - 한국산 자동차 부품 미국 수출,FOB 조건으로 월 500톤 공급 가능합니다. 품질 인증서 및 검사 성적서 구비되어...,2
9077,대량 중동산 원유 파생 제품 수입 희망,품질 등급 A급 기준이며 수입 통관 경험 다수 보유하고 있습니다. L/C at si...,2

In [8]:
post_df.target.value_counts()

target
2    4758
1    2176
0    2144
Name: count, dtype: int64

In [9]:
targets_2 = post_df[post_df.target == 2].sample(2144, random_state=124)
targets_1 = post_df[post_df.target == 1].sample(2144, random_state=124)
targets_0 = post_df[post_df.target == 0]

post_df = pd.concat([targets_0, targets_1])
post_df = pd.concat([post_df, targets_2])
post_df.reset_index(drop=True, inplace=True)
post_df

,title,content,target
0,해외 도박 사이트 총판,불법 총기 부품 구합니다 조용히 거래 원합니다,0
1,010-1234-5678 바로 연락주세요,수익 인증 사진 보내드립니다. 믿고 투자하시면 절대 손해 없습니다.,0
2,빠른 거래 선착순,ㅋㅋㅋ 물건 팝니다 ㅋㅋ 싸요 ㅋㅋ 연락주세요 ㅋㅋ,0
3,무조건 대박 보장 연락주세요,수익 인증 사진 보내드립니다. 믿고 투자하시면 절대 손해 없습니다.,0
4,!!!,불법 총기 부품 구합니다 조용히 거래 원합니다,0
...,...,...,...
6427,수출입 전문 - 중국산 태양광 패널 대량 수입 희망,현지 파트너사와 협력하여 수입 통관 및 내륙 운송까지 일괄 처리 가능합니다. 비용 ...,2
6428,대량 한국산 의약품 원료 수출 가능,"CIF 인천 기준 견적 제공 가능합니다. 최소 주문 수량 50톤이며, 원산지 증명서...",2
6429,신규 바이어 모집 - 중동산 원유 파생 제품 수입 희망,당사 제품은 유럽 CE 인증 및 미국 UL 인증을 보유하고 있어 선진국 수출에 유리...,2
6430,긴급 뉴질랜드산 유제품 정기 수입,"CIF 인천 기준 견적 제공 가능합니다. 최소 주문 수량 50톤이며, 원산지 증명서...",2
6431,대량 멕시코산 아보카도 정기 수입,"현재 재고 2,000톤 보유 중이며 즉시 선적 가능합니다. 시장가 대비 경쟁력 있는...",2

In [10]:
post_df.target.value_counts()

target
0    2144
1    2144
2    2144
Name: count, dtype: int64

In [11]:
pre_p_df = post_df.copy()
pre_p_df['text'] = pre_p_df.title + " " + pre_p_df.content
pre_p_df = pre_p_df.drop(['title', 'content'], axis=1)
pre_p_df

      target                                               text
0          0             해외 도박 사이트 총판 불법 총기 부품 구합니다 조용히 거래 원합니다
1          0  010-1234-5678 바로 연락주세요 수익 인증 사진 보내드립니다. 믿고 투자하...
2          0             빠른 거래 선착순 ㅋㅋㅋ 물건 팝니다 ㅋㅋ 싸요 ㅋㅋ 연락주세요 ㅋㅋ
3          0  무조건 대박 보장 연락주세요 수익 인증 사진 보내드립니다. 믿고 투자하시면 절대 손...
4          0                      !!! 불법 총기 부품 구합니다 조용히 거래 원합니다
...      ...                                                ...
6427       2  수출입 전문 - 중국산 태양광 패널 대량 수입 희망 현지 파트너사와 협력하여 수입 ...
6428       2  대량 한국산 의약품 원료 수출 가능 CIF 인천 기준 견적 제공 가능합니다. 최소 ...
6429       2  신규 바이어 모집 - 중동산 원유 파생 제품 수입 희망 당사 제품은 유럽 CE 인증...
6430       2  긴급 뉴질랜드산 유제품 정기 수입 CIF 인천 기준 견적 제공 가능합니다. 최소 주...
6431       2  대량 멕시코산 아보카도 정기 수입 현재 재고 2,000톤 보유 중이며 즉시 선적 가...

[6432 rows x 2 columns]

In [12]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from kiwipiepy import Kiwi

kiwi = Kiwi()
josa_tags = ["JKS","JKC","JKO","JKG","JKB","JKV","JKQ","JX","JC",
            "EC","EF","EP","ETN","ETM"]

def removes_josa(sentence):
    result = []
    for token in kiwi.tokenize(sentence):
        if token.tag in josa_tags:
            continue

        result.append(token.lemma)
    return " ".join(result)

pre_p_df.text = pre_p_df.text.apply(removes_josa)
pre_p_df

      target                                               text
0          0               해외 도박 사이트 총판 불법 총기 부품 구하다 조용히 거래 원 하
1          0  010-1234-5678 바로 연락 주다 수익 인증 사진 보내다 드리다 . 믿다 투...
2          0             빠르다 거래 선착순 ㅋㅋㅋ 물건 팔다 ㅋㅋ 싸다 ㅋㅋ 연락 주다 ㅋㅋ
3          0  무조건 대 박 보장 연락 주다 수익 인증 사진 보내다 드리다 . 믿다 투자 하 절대...
4          0                        !!! 불법 총기 부품 구하다 조용히 거래 원 하
...      ...                                                ...
6427       2  수출입 전문 - 중국 산 태양광 패널 대량 수입 희망 현지 파트너사 협력 하 수입 ...
6428       2  대량 한국 산 의약품 원료 수출 가능 CIF 인천 기준 견적 제공 가능 하 . 최소...
6429       2  신규 바이어 모집 - 중동 산 원유 파생 제품 수입 희망 당사 제품 유럽 CE 인증...
6430       2  긴급 뉴질랜드 산 유제품 정기 수입 CIF 인천 기준 견적 제공 가능 하 . 최소 ...
6431       2  대량 멕시코 산 아보카도 정기 수입 현재 재고 2,000 톤 보유 중 이다 즉시 선...

[6432 rows x 2 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
train_test_split(pre_p_df.text, pre_p_df.target, stratify=pre_p_df.target, test_size=0.2, random_state=124)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

m_nb_pipe = Pipeline(
    [
        ('count_vectorizer', CountVectorizer()), 
        ('multinomial_NB', MultinomialNB(alpha=0.2))
    ]
)

m_nb_pipe.fit(X_train.values, y_train)

Pipeline(steps=[('count_vectorizer', CountVectorizer()),
                ('multinomial_NB', MultinomialNB(alpha=0.2))])

In [15]:
m_nb_pipe.score(X_test.values, y_test)

0.9914529914529915

In [16]:
# 정상 예측
prediction = m_nb_pipe.predict(['호주산 철광석 장기 계약 바이어 모집 CIF 부산 기준 월 300톤 정기 구매 희망합니다. T/T 결제 가능하며 원산지 증명서 및 선적 서류 완비 필수입니다. ISO 인증 보유 업체 우선 협의하겠습니다.'])
prediction

array([2])

In [20]:
# 의심 예측
prediction = m_nb_pipe.predict(['창고에 한가득 있는데 자리가 없어서 빨리 비워야 해요. 뭔지는 연락주시면 말씀드릴게요. 가격은 솔직히 그냥 드리는 수준입니다. 진지한 분만 연락주세요.'])
prediction

array([1])

In [18]:
# 검표 필요 예측
prediction = m_nb_pipe.predict(['부업으로 월 800 버는 방법 공유합니다부업으로 월 800 버는 방법 공유합니다 저도 처음엔 반신반의했는데 세 달째 매달 800 이상 찍히고 있어요. 불법 아니고 특별한 기술도 필요 없습니다. 자세한 방법은 오픈채팅방 들어오시면 설명드려요. 링크는 쪽지로 드립니다.'])
prediction

array([0])

In [19]:
import joblib

joblib.dump(m_nb_pipe, 'post_score.pkl')

['post_score.pkl']